source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve

gem "jekyll", "~> 4.2"
gem "logger"
gem "fiddle"
gem "bigdecimal"
gem "rake" # required at runtime by just-the-docs via jekyll-remote-theme

group :jekyll_plugins do
  gem "jekyll-remote-theme", "= 0.4.3"
  gem "jekyll-sass-converter", "~> 2.2"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
  gem "jekyll-sitemap"
  gem "jekyll-relative-links"
  gem "jekyll-redirect-from"
  gem "jekyll-default-layout"
  gem "jekyll-gfm-admonitions"
end

platforms :windows do
  gem "wdm", "~> 0.1"
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
